"""Changed to a mutable dict for followups

Revision ID: 134828dfc9ca
Revises: f78dbf1aae22
Create Date: 2025-09-11 11:13:30.634160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134828dfc9ca'
down_revision: Union[str, Sequence[str], None] = 'f78dbf1aae22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
