"""Updated to include other fields with explanation

Revision ID: 1ae7f5eb1e4e
Revises: 989ad3f8c122
Create Date: 2025-09-12 18:05:11.307211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae7f5eb1e4e'
down_revision: Union[str, Sequence[str], None] = '989ad3f8c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('incident_other_exp', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('injury_other_exp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'injury_other_exp')
    op.drop_column('incidents', 'incident_other_exp')
    # ### end Alembic commands ###
