"""Matched formatting with prompts file

Revision ID: 48b9434cfd73
Revises: 8474e87f5367
Create Date: 2025-09-03 19:19:30.500554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b9434cfd73'
down_revision: Union[str, Sequence[str], None] = '8474e87f5367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('person_involved_name', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('person_involved_age', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('person_involved_phone_number', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('person_involved_guest_of', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('person_involved_address', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('person_involved_guardian', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('was_employee_involved', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('was_security_contacted', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('was_law_contacted', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('was_transported_ambulance', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('address_of_incident', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('witness_phone', sa.String(), nullable=True))
    op.drop_column('incidents', 'employee_involved')
    op.drop_column('incidents', 'witness_phone_number')
    op.drop_column('incidents', 'involved_age')
    op.drop_column('incidents', 'where_incident_occurred')
    op.drop_column('incidents', 'law_contacted')
    op.drop_column('incidents', 'involved_guardian')
    op.drop_column('incidents', 'transported_ambulance')
    op.drop_column('incidents', 'security_contacted')
    op.drop_column('incidents', 'involved_address')
    op.drop_column('incidents', 'involved_name')
    op.drop_column('incidents', 'involved_guest_of')
    op.drop_column('incidents', 'involved_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('involved_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('involved_guest_of', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('involved_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('involved_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('security_contacted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('transported_ambulance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('involved_guardian', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('law_contacted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('where_incident_occurred', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('involved_age', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('witness_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('employee_involved', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'witness_phone')
    op.drop_column('incidents', 'address_of_incident')
    op.drop_column('incidents', 'was_transported_ambulance')
    op.drop_column('incidents', 'was_law_contacted')
    op.drop_column('incidents', 'was_security_contacted')
    op.drop_column('incidents', 'was_employee_involved')
    op.drop_column('incidents', 'person_involved_guardian')
    op.drop_column('incidents', 'person_involved_address')
    op.drop_column('incidents', 'person_involved_guest_of')
    op.drop_column('incidents', 'person_involved_phone_number')
    op.drop_column('incidents', 'person_involved_age')
    op.drop_column('incidents', 'person_involved_name')
    # ### end Alembic commands ###
