"""Changed to sqlAlchemy 2.0 style relationship

Revision ID: 4bec165a9494
Revises: 7f961a01c875
Create Date: 2025-09-29 21:49:08.120876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bec165a9494'
down_revision: Union[str, Sequence[str], None] = '7f961a01c875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
