"""create incidents table

Revision ID: 5d2748b1518d
Revises: b7109bb1e1aa
Create Date: 2025-09-03 16:47:49.219968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2748b1518d'
down_revision: Union[str, Sequence[str], None] = 'b7109bb1e1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('creator_phone', sa.String(), nullable=False),
    sa.Column('involved_name', sa.String(), nullable=False),
    sa.Column('involved_age', sa.String(), nullable=False),
    sa.Column('involved_phone', sa.String(), nullable=False),
    sa.Column('involved_guest_of', sa.String(), nullable=False),
    sa.Column('involved_address', sa.String(), nullable=False),
    sa.Column('involved_guardian', sa.String(), nullable=False),
    sa.Column('date_of_incident', sa.String(), nullable=False),
    sa.Column('time_of_incident', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('incident_address', sa.String(), nullable=False),
    sa.Column('incident_summary', sa.String(), nullable=False),
    sa.Column('body_part_afflicted', sa.String(), nullable=False),
    sa.Column('employee_involved', sa.String(), nullable=False),
    sa.Column('security_contacted', sa.String(), nullable=False),
    sa.Column('law_contacted', sa.String(), nullable=False),
    sa.Column('transported_ambulance', sa.String(), nullable=False),
    sa.Column('ambulance_to_where', sa.String(), nullable=False),
    sa.Column('type_of_incident', sa.String(), nullable=False),
    sa.Column('where_incident_occurred', sa.String(), nullable=False),
    sa.Column('signs_symptoms', sa.String(), nullable=False),
    sa.Column('allergies', sa.String(), nullable=False),
    sa.Column('medications', sa.String(), nullable=False),
    sa.Column('past_history', sa.String(), nullable=False),
    sa.Column('last_food_drink', sa.String(), nullable=False),
    sa.Column('events_leading_up', sa.String(), nullable=False),
    sa.Column('type_of_injury', sa.String(), nullable=False),
    sa.Column('employee_completing_report', sa.String(), nullable=False),
    sa.Column('date_of_report', sa.String(), nullable=False),
    sa.Column('witness', sa.String(), nullable=False),
    sa.Column('witness_phone_number', sa.String(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
