"""Changed to sqlAlchemy 2.0 style relationship

Revision ID: 7f961a01c875
Revises: 28c2697c8ee0
Create Date: 2025-09-29 21:48:23.034340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f961a01c875'
down_revision: Union[str, Sequence[str], None] = '28c2697c8ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
