"""made most incident fields nullable

Revision ID: 8474e87f5367
Revises: 9a1817aee7b7
Create Date: 2025-09-03 16:54:40.073232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8474e87f5367'
down_revision: Union[str, Sequence[str], None] = '9a1817aee7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'involved_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'involved_age',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'involved_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'involved_guest_of',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'involved_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'involved_guardian',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'date_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'time_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'facility_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'incident_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'incident_summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'body_part_afflicted',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'employee_involved',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'security_contacted',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'law_contacted',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'transported_ambulance',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'ambulance_to_where',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'type_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'where_incident_occurred',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'signs_symptoms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'allergies',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'medications',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'past_history',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'last_food_drink',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'events_leading_up',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'type_of_injury',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'employee_completing_report',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'date_of_report',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'witness',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'witness_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'witness_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'witness',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'date_of_report',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'employee_completing_report',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'type_of_injury',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'events_leading_up',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'last_food_drink',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'past_history',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'medications',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'allergies',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'signs_symptoms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'where_incident_occurred',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'type_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'ambulance_to_where',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'transported_ambulance',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'law_contacted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'security_contacted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'employee_involved',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'body_part_afflicted',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'incident_summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'incident_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'facility_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'time_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'date_of_incident',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_guardian',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_guest_of',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_age',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'involved_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
