"""Added locations k,v pair

Revision ID: 8867a4823f54
Revises: fe959599a8fe
Create Date: 2025-10-07 19:51:44.970403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8867a4823f54'
down_revision: Union[str, Sequence[str], None] = 'fe959599a8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    op.create_table('regions',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_regions_slug'), 'regions', ['slug'], unique=True)
    op.create_table('lifeguards',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_lifeguards_phone'), 'lifeguards', ['phone'], unique=True)
    op.create_table('manager_region',
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.pk'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_region')
    op.drop_index(op.f('ix_lifeguards_phone'), table_name='lifeguards')
    op.drop_table('lifeguards')
    op.drop_index(op.f('ix_regions_slug'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
