"""Added location of incident

Revision ID: 989ad3f8c122
Revises: 134828dfc9ca
Create Date: 2025-09-12 15:46:10.786594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989ad3f8c122'
down_revision: Union[str, Sequence[str], None] = '134828dfc9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('was_911_contacted', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('location_of_incident', sa.String(), nullable=True))
    op.drop_column('incidents', 'was_law_contacted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('was_law_contacted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'location_of_incident')
    op.drop_column('incidents', 'was_911_contacted')
    # ### end Alembic commands ###
