"""Changed to a mutable dict for followups

Revision ID: a11504ab0c1d
Revises: d2ff62fd80cc
Create Date: 2025-09-11 11:11:12.639227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11504ab0c1d'
down_revision: Union[str, Sequence[str], None] = 'd2ff62fd80cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
