"""Add followups column

Revision ID: d2ff62fd80cc
Revises: fb8fc4b0637c
Create Date: 2025-09-11 10:36:56.867551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ff62fd80cc'
down_revision: Union[str, Sequence[str], None] = 'fb8fc4b0637c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('followups', sa.JSON(), nullable=False))
    op.drop_column('incidents', 'address_of_incident')
    op.drop_column('incidents', 'date_of_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date_of_report', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('address_of_incident', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'followups')
    # ### end Alembic commands ###
